### ISSUE TITLE
[Map] Map画面において、閲覧モードから編集モードに切り替えたときにツリーの展開を保持してほしい

### ISSUE THREAD

**Issue by okuruma** [endosnipe/ENdoSnipe#289]
[Map]
Map画面において、閲覧モードから編集モードに切り替えたときに
ツリーの展開を保持してほしい
 
■動作環境 (Environment)
 ENdoSnipe Agent Ver.5.0.3_019
 Apache Tomcat/7.0.29
 Windows7

【1.現象 (Fact)】
Map画面において、閲覧モードから編集モードに切り替えたときに
ツリーが閉じる。
ユーザとしては、閲覧モードで見たシグナルやグラフを
マップへ追加したい時にツリーが閉じない方が嬉しい

【2.再現手順 (Operations)】
 1) Map画面を閲覧モードで開く
 2) ツリーを展開する
 3) 編集モードに切り替える

【3.期待結果 (Expected result)】
閲覧モードから編集モードに切り替えた際に
ツリーが展開した状況を保持すること

**Comment by s-fujii200** [comment]
参照モードでツリーを表示しない仕様としたため、本チケットはクローズする。
