### ISSUE TITLE
[Map] Map画面において編集モードから閲覧モードに切り替えるとき、マップの変更があった際に、保存するかどうか確認するダイアログが出て欲しい。

### ISSUE THREAD

**Issue by okuruma** [endosnipe/ENdoSnipe#290]
[Map]
Map画面において編集モードから閲覧モードに切り替えるとき、
マップの変更があった際に、保存するかどうか確認する
ダイアログが出て欲しい。

■動作環境 (Environment)
ENdoSnipe Agent Ver.5.0.3_019
Apache Tomcat/7.0.29
Windows7

【1.現象 (Fact)】
Map画面において、編集モードから閲覧モードに切り替えたときに
Mapに編集があっても保存されない。

【2.再現手順 (Operations)】
1) Mapを編集モードで開く
2) グラフやシグナルを追加する
3) モード切替ボタンを押下する

【3.期待結果 (Expected result)】
ユーザが、編集モードから閲覧モードに
変更状態を保存せずに切り替えようとしたときには、
保存するか尋ねるダイアログが出ること

**Comment by s-fujii200** [comment]
確認しましたが、以下の場合に、ダイアログが出ません。

1.Dashboardで、「01_System」を選択。
2.編集モードアイコンを選択する。
3.テキストオブジェクトを追加する。
4.閲覧モードアイコンを選択する。

グラフの移動ではダイアログが出るので、オブジェクトの配置の場合の考慮が漏れているように見えます。
