### ISSUE TITLE
[Dashboard] Dashboard編集モードにおける、編集アイコンのツールチップが見えない

### ISSUE THREAD

**Issue by s-fujii200** [endosnipe/ENdoSnipe#618]
■動作環境
Apache Tomcat/7.0.29
Windows7, Firefox 34.0.5

【1.現象】
Dashboardを編集モードにすると、編集アイコンのツールチップが薄くて見えない。

【2.再現手順】
1.Dashboardを開く。
2.編集アイコンを選択する。

【3.期待結果】
ツールチップが見やすくなること。
![default](https://cloud.githubusercontent.com/assets/3915732/5699959/6d817846-9a77-11e4-8759-de6de598f8f0.png)

**Comment by miyasakago** [comment]
issue #648 で本件については改善済みのため、クローズする。
以下、改善後のキャプチャ。
![618_](https://cloud.githubusercontent.com/assets/2400926/9273703/e26a25f4-42c9-11e5-8833-c4cf3e90a48f.png)
