### ISSUE TITLE
[Threaddump] スレッドダンプで、<<javelin.EventInfo_START>>　となるべきところが、ブラウザ上で見ると、<>になる。

### ISSUE THREAD

**Issue by s-fujii200** [endosnipe/ENdoSnipe#623]
■動作環境
Apache Tomcat/7.0.29
Windows7, Firefox 34.0.5

【1.現象】
スレッドダンプを表示すると、<<javelin.EventInfo_START>>　となるべきところが、ブラウザ上で見ると、<>になる。

【2.再現手順】
1.Explore画面を開く。
2.Threaddumpタブを選択する。
3.任意のThreaddumpを開く。

【3.期待結果】
スレッドダンプの結果が、JVNファイルと同じように表示されること。
![threaddump](https://cloud.githubusercontent.com/assets/3915732/5700041/0cd162e8-9a79-11e4-93cf-ea77900888d9.png)

**Comment by ryokato** [comment]
修正しました。
![623_](https://cloud.githubusercontent.com/assets/3169718/9705170/480421ce-54f6-11e5-979d-5b20e92d980c.PNG)
