### ISSUE TITLE
[Javelin]実行計画を出力すると、DataCollectorでエラーが出力される。

### ISSUE THREAD

**Issue by s-fujii200** [endosnipe/ENdoSnipe#643]
■動作環境
Apache Tomcat/7.0.29
Windows7, Firefox 34.0.5

【1.現象】
JDBCJavelinで実行計画取得するモードにすると、
キーの一意性制約エラーが発生する。

【2.再現手順】
1.以下を設定する。
javelin.jdbc.enable=true
javelin.jdbc.recordExecPlan=true

2.アプリケーションをしばらく動作させる。

【3.期待結果】
エラーが表示されない。

**Comment by miyasakago** [comment]
実行計画取得時のキーの一意性制約エラーが発生しないように修正した為、
本チケット指摘のエラーは発生しなくなった。

また、画面UIとしても、
『 Query : Query Plan : Stack Trace = 1 : 1 : n 』を表現した。
