### ISSUE TITLE
[Dashboard] Ver6.0新規画面のレイアウト改善

### ISSUE THREAD

**Issue by s-fujii200** [endosnipe/ENdoSnipe#663]
Ver6.0にて追加した新規画面のレイアウトを改善する。
＃ボタンが統一されていない、レイアウトが揃っていないなど。

1) Profilerビュー
2) Controllerビュー
3) Downloadビュー

以下も合わせて対応する。
4) 「Scheduling Report」という名称を「Periodic report」に変更する。
5) Scheduling Reportの時刻が1～24になっているが、0～23に変更する。
6) 欠測で0を挿入する期間を長くする。
　ダッシュボードで度々欠測が発生して見栄えが悪いため。
7)　02_JavaProcessのヒープメモリのグラフに最大値を出力する。

**Comment by miyasakago** [comment]
以下のレイアウトを改善を行った。

1) Profilerビュー
　・ボタンを他のボタンと統一した
　・適切なマージンを入れた
2) Controllerビュー
　・ボタンを他のボタンと統一した
　・適切なマージンを入れた
　・一覧テーブルにページャを付けた
3) Downloadビュー
　・検索フォームのレイアウト改善
　・ボタンを他のボタンと統一した
　・適切なマージンを入れた
4) 「Scheduling Report」という名称を「Periodic report」に変更した
5) Scheduling Reportの時刻が1～24になっているのを、0～23に変更した
6) "GraphTree"と"DashboardView"という不要なパースペクティブのタイトルを削除した
