### ISSUE TITLE
[ENdoSnipeCommunicator]電文サイズの削減

### ISSUE THREAD

**Issue by s-fujii200** [endosnipe/ENdoSnipe#692]
電文サイズが大きくなっているので削減する。

以下、削減案。

1)エージェント名の短縮化
2)系列名を系列IDのみでやり取りを行い、クライアントで変換する。

**Comment by miyasakago** [comment]
Javelin-DataCollector間の電文サイズの削減を行った。

電文サイズの削減方法は以下。
①同じ電文内にある項目名同士の共通の文字列数が50以上の場合に、
　共通部分の文字列をキー文字列に置き換えることで電文サイズを圧縮するようにした。
②キー文字列と共通部分の文字列は同じ電文内に持たせることで、
　電文内の情報だけで情報を復元できるようにした。
